apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - name: 4111-3111
    port: {{ .Values.service.port}} 
    protocol: TCP
    targetPort: {{ .Values.service.targetPort}} 
  selector:
    app: techtrends
  type: ClusterIP
status:
  loadBalancer: {}