namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

image:
  repository: jaikansra/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limits:
    memory: "256Mi"
    cpu: "500m"


