namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  type: ClusterIP
  protocol: TCP

image:
  repository: jaikansra/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

ports:
  containerPort: 3111
  protocol: TCP
  livenessProbe:
    httpGet:
    path: /healthz
    port: 3111
  readinessProbe:
    httpGet:
    path: /healthz
    port: 3111

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    memory: "128Mi"
    cpu: "500m"


